package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;

    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    
    private JoinPredicate _oppai;
    private DbIterator _oppai1;
    private DbIterator _oppai2;
    private Tuple _left_oppai;
    
    public Join(JoinPredicate p, DbIterator child1, DbIterator child2) {
        // some code goes here
    	_oppai = p;
    	_oppai1 = child1;
    	_oppai2 = child2;
    }

    public JoinPredicate getJoinPredicate() {
        // some code goes here
        return _oppai;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        // some code goes here
        return null;
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        // some code goes here
        return null;
    }

    /**
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // some code goes here
        return TupleDesc.merge(_oppai1.getTupleDesc(), _oppai2.getTupleDesc());
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // some code goes here
    	_oppai1.open();
    	_oppai2.open();
    	super.open();
    	_left_oppai = _oppai1.next();
    }

    public void close() {
        // some code goes here
    	_oppai1.close();
    	_oppai2.close();
    	super.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // some code goes here
    	_oppai1.rewind();
    	_oppai2.rewind();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // some code goes here
    	while(_oppai2.hasNext() || _oppai1.hasNext()){
    		if (!_oppai2.hasNext()){
    			_left_oppai = _oppai1.next();
    			_oppai2.rewind();
    		}
    		Tuple t2 = _oppai2.next();
    		if (_oppai.filter(_left_oppai, t2)){
    			Tuple res = new Tuple(TupleDesc.merge(_left_oppai.getTupleDesc(), t2.getTupleDesc()));
    			for (int i = 0; i < _left_oppai.getTupleDesc().numFields(); i++){
    				res.setField(i, _left_oppai.getField(i));
    			}
    			for (int i = 0; i < t2.getTupleDesc().numFields(); i++){
    				res.setField(_left_oppai.getTupleDesc().numFields() + i, t2.getField(i));
    			}
    			return res;
    		}
    	}
        return null;
    }

    @Override
    public DbIterator[] getChildren() {
        // some code goes here
    	DbIterator[] dbI = {_oppai1, _oppai2};
        return dbI;
    }

    @Override
    public void setChildren(DbIterator[] children) {
        // some code goes here
    	_oppai1 = children[0];
    	_oppai2 = children[1];
    }

}
